# Generated by Django 3.2 on 2021-05-01 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('card_choice', models.CharField(choices=[('aadhar card', 'aadhar card'), ('pan card', 'pan card'), ('passport card', 'passport card')], default='aadhar card', max_length=20)),
                ('file_uploaded', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_name', models.CharField(default=None, max_length=100)),
                ('passport_gender', models.CharField(default=None, max_length=100)),
                ('passport_num', models.TextField(default=None, null=True)),
                ('passport_dob', models.TextField(default=None, null=True)),
                ('passport_expiry_date', models.TextField(default=None, null=True)),
                ('passport_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.kyc')),
            ],
        ),
        migrations.CreateModel(
            name='Pan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_name', models.TextField(default=None, null=True)),
                ('pan_fname', models.TextField(default=None, null=True)),
                ('pan_num', models.TextField(default=None, null=True)),
                ('pan_dob', models.TextField(default=None, null=True)),
                ('pan_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.kyc')),
            ],
        ),
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(default=None, max_length=100)),
                ('dob', models.TextField(default=None, null=True)),
                ('num', models.TextField(default=None, null=True)),
                ('kyc_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.kyc')),
            ],
        ),
    ]
