# Generated by Django 3.2 on 2021-05-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='face_matched',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
